stages:
  - build
  - deploy

install:
  image: node:latest
  stage: build
  script:
    - npm i
  artifacts:
    paths:
      - node_modules/
  expire_in: 1 day

build-frontend:
  image: node:latest
  stage: build
  script:
    - npm run build:frontend
  artifacts:
    paths:
      - dist/

deploy-production:
  image: ebiwd/alpine-ssh:latest
  stage: deploy
  script:
    - eval "$(ssh-agent)"
    - ssh-add <(echo "$PRODUCTION_PRIVATE_KEY")
    - ssh -p22 gitlab@web.arvale.world "cd /srv/web && git pull && npm i"
    - scp -P22 -r dist/* gitlab@web.arvale.world:/srv/web/dist
