stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm i
    - npm run build:frontend
    - npm run build:api
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy:
  image: ebiwd/alpine-ssh:latest
  stage: deploy
  script:
    - eval "$(ssh-agent)"
    - ssh-add <(echo "$PRODUCTION_PRIVATE_KEY")
    - scp -P22 -r dist/* gitlab@web.arvale.world:/srv/web
