stages:
  - build
  - deploy

build-frontend:
  image: node:latest
  stage: build
  before_script:
    - npm i
  script:
    - npm run build:frontend
  cache:
    paths:
    - node_modules/
  artifacts:
    paths:
      - dist/

deploy-production:
  image: sickp/docker-alpine-sshd:latest
  stage: deploy
  script:
    - ssh-add <(echo "$PRODUCTION_PRIVATE_KEY")
    - ssh -p22 gitlab@web.arvale.world "cd /srv/web && npm i"
    - scp -P22 -r dist/* gitlab@web.arvale.world:/srv/web/dist
