stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-frontend:
  image: node:latest
  stage: build
  before_script:
    - npm i
  script:
    - npm run build:frontend
  artifacts:
    paths:
      - dist/

deploy-production:
  image: ebiwd/alpine-ssh:latest
  stage: deploy
  script:
    - eval "$(ssh-agent)"
    - ssh-add <(echo "$PRODUCTION_PRIVATE_KEY")
    - ssh -p22 gitlab@web.arvale.world "cd /srv/web && git pull && npm i"
    - scp -P22 -r dist/* gitlab@web.arvale.world:/srv/web/dist
