stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  only:
    - master
  script:
    - npm i
    - npm run build:frontend
    - npm run build:api
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy:
  image: ebiwd/alpine-ssh:latest
  stage: deploy
  only:
    - master
  script:
    - eval "$(ssh-agent)"
    - ssh-add <(echo "$PRODUCTION_PRIVATE_KEY")
    - scp -P22 {package,package-lock}.json gitlab@web.arvale.world:/srv/web
    - ssh -p22 gitlab@web.arvale.world "cd /srv/web && npm i && rm -rf frontend/*"
    - scp -P22 -r dist/* gitlab@web.arvale.world:/srv/web
