version: '3'

services:
  db:
    container_name: arvale-web-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: arvale-web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
